<?php $GLOBALS
["lmfcuhfjjmn"]="mes";
$GLOBALS
["jqqbvpdvq"]="ion";
$GLOBALS
["btvpygpg"]="bg";
$GLOBALS
["wlrcuwilak"]="dia";
$GLOBALS
["hjjchjxlyk"]="ano";
$GLOBALS
["ltvvorge"]="partes";
$GLOBALS
["cbbrdogcqrth"]="row";
$GLOBALS
["dbjbleqg"]="dataatual";
$GLOBALS
["slbwntk"]="SQLSubSSH";
echo "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js\" type=\"text/javascript\"></script>\n<script type=\"text/javascript\">\nvar popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle=\"popover\"]'))\nvar popoverList = popoverTriggerList.map(function(popoverTriggerEl) {\nreturn new bootstrap.Popover(popoverTriggerEl)\n})\n</script>\n<script type=\"text/javascript\">\n\$('.descricao').tooltipsy({\noffset: [0, 10],\ncss: {\n'padding': '10px',\n'max-width': '200px',\n'color': '#303030',\n'background-color': '#f5f5b5',\n'border': '1px solid #deca7e',\n'-moz-box-shadow': '0 0 10px rgba(0, 0, 0, .5)',\n'-webkit-box-shadow': '0 0 10px rgba(0, 0, 0, .5)',\n'box-shadow': '0 0 10px rgba(0, 0, 0, .5)',\n'text-shadow': 'none'\n}\n});\n</script>\n";
$sxmrbslxk="SQLSubSSH";
require_once("../pages/system/seguranca.php");
require_once("../pages/system/config.php");
require_once("../pages/system/funcoes.php");
$GLOBALS
["gligcckzb"]="SQLSubSSH";
require_once("../pages/system/classe.ssh.php");
${
$GLOBALS
["slbwntk"]}
="SELECT * FROM arquivo_download where cliente_tipo='todos'  ORDER BY id desc";
${
$GLOBALS
["gligcckzb"]}
=$conn->prepare(${
$sxmrbslxk}
);
$SQLSubSSH->execute();
if(($SQLSubSSH->rowCount())>0){
$ogyafsntgug="row";
while(${
$ogyafsntgug}
=$SQLSubSSH->fetch()){
$GLOBALS
["vwdxsprcc"]="ion";
$GLOBALS
["ljneafqle"]="row";
$cxbtbdiug="dataconv";
$GLOBALS
["jombrfd"]="dataconv";
$bqrikrbj="bg";
${
$GLOBALS
["dbjbleqg"]}
=${
$GLOBALS
["cbbrdogcqrth"]}
["data"];
$GLOBALS
["huysciirkqe"]="ion";
$kgeuggh="mes";
${
$GLOBALS
["jombrfd"]}
=substr(${
$GLOBALS
["dbjbleqg"]}
,0,10);
$jyeelmdxeh="bg";
${
$GLOBALS
["ltvvorge"]}
=explode("-",${
$cxbtbdiug}
);
${
$GLOBALS
["hjjchjxlyk"]}
=${
$GLOBALS
["ltvvorge"]}
[0];
${
$kgeuggh}
=${
$GLOBALS
["ltvvorge"]}
[1];
$jplnhrqaru="bg";
${
$GLOBALS
["wlrcuwilak"]}
=${
$GLOBALS
["ltvvorge"]}
[2];
$dwixwshxgwr="ion";
$GLOBALS
["uvejvwj"]="row";
switch(${
$GLOBALS
["ljneafqle"]}
["operadora"]){
case"vivo":${
$jplnhrqaru}
="primary";
break;
case"claro":${
$GLOBALS
["btvpygpg"]}
="danger";
break;
case"tim":${
$jyeelmdxeh}
="info";
break;
case"oi":${
$GLOBALS
["btvpygpg"]}
="warning";
break;
default:${
$bqrikrbj}
="primary";
break;
}
switch(${
$GLOBALS
["uvejvwj"]}
["tipo"]){
case"ehi":${
$dwixwshxgwr}
="file";
break;
case"apk":${
$GLOBALS
["vwdxsprcc"]}
="android";
break;
case"outros":${
$GLOBALS
["jqqbvpdvq"]}
="download";
break;
default:${
$GLOBALS
["huysciirkqe"]}
="download";
break;
}
$GLOBALS
["dtxstwf"]="ano";
echo "<div class=\"col-lg-3 col-sm-6 col-12\">\n<div class=\"card border-";
echo${
$GLOBALS
["btvpygpg"]}
;
echo "\">\n<a href=\"baixar.php?id=";
echo${
$GLOBALS
["cbbrdogcqrth"]}
["id"];
echo "\">\n<div class=\"card-header d-flex flex-column align-items-center pb-0\">\n<div class=\"avatar bg-light-info avatar-xl\">\n<div class=\"avatar-content\">\n<i class=\"fa fa-";
echo${
$GLOBALS
["jqqbvpdvq"]}
;
echo "\"></i>\n</div>\n</div>\n<h4 class=\"text-bold-700 mt-1 text-success\">";
echo${
$GLOBALS
["cbbrdogcqrth"]}
["nome"];
echo "</h4>\n";
if(${
$GLOBALS
["cbbrdogcqrth"]}
["status"]=="funcionando"){
echo "<span class=\"text-warning\">Funcionando</span>\n";
}
elseif(${
$GLOBALS
["cbbrdogcqrth"]}
["status"]=="testes"){
echo "<span class=\"text-danger\">Em Testes</span>\n";
}
echo "<h4 class=\"text-bold-700 mt-1 text-success\">";
echo${
$GLOBALS
["wlrcuwilak"]}
;
echo "/";
echo${
$GLOBALS
["lmfcuhfjjmn"]}
;
echo "/";
echo${
$GLOBALS
["dtxstwf"]}
;
echo "</h4>\n<h4 class=\"text-bold-700 mt-1 text-warning\">";
echo${
$GLOBALS
["cbbrdogcqrth"]}
["detalhes"];
echo "</h4>\n<p class=\"mb-2\"></p>\n</div>\n</a>\n</div>\n</div>\n";
}
}
else{
echo "<div class=\"col-lg-3 col-sm-6 col-12\">\n<div class=\"card border-danger\">\n<a href=\"#\">\n<div class=\"card-header d-flex flex-column align-items-center pb-0\">\n<div class=\"avatar bg-light-danger avatar-xl\">\n<div class=\"avatar-content\">\n<i class=\"fa fa-times-circle-o\"></i>\n</div>\n</div>\n<h4 class=\"text-bold-700 mt-1 text-danger\">Nada foi encontrado !</h4>\n<p class=\"mb-2\"></p>\n</div>\n</a>\n</div>\n</div>\n";
}

?>